version: '3.7'

services:
  db:
    env_file: .env
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql_data:/var/lib/mysql"
      - "./data/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    
      
  